---
- name: Sample aaacertparams playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaacertparams
      delegate_to: localhost
      netscaler.adc.aaacertparams:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        usernamefield: Subject:CN
        groupnamefield: Subject:OU
        defaultauthenticationgroup: abc
