---
- name: Sample aaagroup playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaagroup
      delegate_to: localhost
      netscaler.adc.aaagroup:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        groupname: External
