---
- name: Sample aaagroup_vpnsessionpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaagroup_vpnsessionpolicy_binding
      delegate_to: localhost
      netscaler.adc.aaagroup_vpnsessionpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        groupname: External
        policy: External_receiver_session_pol
        priority: '110'
        gotopriorityexpression: NEXT
