---
- name: Sample aaagroup_vpnintranetapplication_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaagroup_vpnintranetapplication_binding
      delegate_to: localhost
      netscaler.adc.aaagroup_vpnintranetapplication_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        groupname: group1
        intranetapplication: intra_app2
