---
- name: Sample aaaldapparams playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaaldapparams
      delegate_to: localhost
      netscaler.adc.aaaldapparams:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        sectype: PLAINTEXT
