---
- name: Sample aaaparameter playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaaparameter
      delegate_to: localhost
      netscaler.adc.aaaparameter:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        maxaaausers: '4294967295'
        aaasessionloglevel: DEBUG
        aaadloglevel: ALERT
