---
- name: Sample aaapreauthenticationaction playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaapreauthenticationaction
      delegate_to: localhost
      netscaler.adc.aaapreauthenticationaction:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: preact
        preauthenticationaction: ALLOW
