---
- name: Sample aaaradiusparams playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaaradiusparams
      delegate_to: localhost
      netscaler.adc.aaaradiusparams:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        serverip: 10.102.25.64
        radkey: test123
