---
- name: Sample aaauser_authorizationpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaauser_authorizationpolicy_binding
      delegate_to: localhost
      netscaler.adc.aaauser_authorizationpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        username: ns
        policy: deny_raaga
