---
- name: Sample aaauser_vpnsessionpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaauser_vpnsessionpolicy_binding
      delegate_to: localhost
      netscaler.adc.aaauser_vpnsessionpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        username: q11
        policy: csec
