---
- name: Sample aaauser playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure aaauser
      delegate_to: localhost
      netscaler.adc.aaauser:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        username: msiuser1
