---
- name: Sample appfwsettings playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwsettings
      delegate_to: localhost
      netscaler.adc.appfwsettings:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        sessiontimeout: '180'
