---
- name: Sample appfwgrpcwebjsoncontenttype playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwgrpcwebjsoncontenttype
      delegate_to: localhost
      netscaler.adc.appfwgrpcwebjsoncontenttype:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        grpcwebjsoncontenttypevalue: application/grpc-web+json
