---
- name: Sample appflowpolicylabel playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appflowpolicylabel
      delegate_to: localhost
      netscaler.adc.appflowpolicylabel:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        labelname: ia_appflow_polabl3
