---
- name: Sample appfwprofile_fieldformat_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwprofile_fieldformat_binding
      delegate_to: localhost
      netscaler.adc.appfwprofile_fieldformat_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: Test_profile
        fieldformat: text_area
        formactionurl_ff: ^http://test.net/credit.html$
        fieldtype: CM1454107840652651
        fieldformatminlength: '1'
        fieldformatmaxlength: '78'
        isregex_ff: NOTREGEX
