---
- name: Sample appfwprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwprofile
      delegate_to: localhost
      netscaler.adc.appfwprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: pr_appfw
        starturlaction:
          - learn
          - log
          - stats
