---
- name: Sample appfwmultipartformcontenttype playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwmultipartformcontenttype
      delegate_to: localhost
      netscaler.adc.appfwmultipartformcontenttype:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        multipartformcontenttypevalue: multipart/form-data.*
        isregex: REGEX
