---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | appflowparam
      delegate_to: localhost
      netscaler.adc.appflowparam:
        state: present
        observationpointid: '2370493962'
