---
- name: Sample appfwxmlcontenttype playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwxmlcontenttype
      delegate_to: localhost
      netscaler.adc.appfwxmlcontenttype:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        xmlcontenttypevalue: END
        isregex: NOTREGEX
