---
- name: Sample appfwprofile_logexpression_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwprofile_logexpression_binding
      delegate_to: localhost
      netscaler.adc.appfwprofile_logexpression_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: profile2
        logexpression: xyz
        as_logexpression: http.req.url
