---
- name: Sample appflowaction playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appflowaction
      delegate_to: localhost
      netscaler.adc.appflowaction:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: af_action_log_10.189.64.10_nop
        collectors:
          - af_collector_logstream_10.189.64.10
