---
- name: Sample appfwprofile_creditcardnumber_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwprofile_creditcardnumber_binding
      delegate_to: localhost
      netscaler.adc.appfwprofile_creditcardnumber_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: Test_profile
        creditcardnumber: '348238190706900'
        creditcardnumberurl: ^http://test.net/credit.html$
