---
- name: Sample appfwprofile_xmlvalidationurl_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwprofile_xmlvalidationurl_binding
      delegate_to: localhost
      netscaler.adc.appfwprofile_xmlvalidationurl_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: XMLSchema_2
        xmlvalidationurl: .*
        xmlrequestschema: Xml_Schema_2
        xmlresponseschema: Xml_Schema_2
