---
- name: Sample appfwxmlschema playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwxmlschema
      delegate_to: localhost
      netscaler.adc.appfwxmlschema:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        src: http://10.217.30.16/testsite/Signatures/44_38_1_36/schema.xml
        name: lower_schema
        nitro_operation: import
        '#nitro_operation': import
