---
- name: Sample appfwfieldtype playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwfieldtype
      delegate_to: localhost
      netscaler.adc.appfwfieldtype:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: CM1454107840652651
        regex: ^[A-Z\\a-z]+$
        priority: '10'
