---
- name: Sample appfwconfidfield playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwconfidfield
      delegate_to: localhost
      netscaler.adc.appfwconfidfield:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        fieldname: ia_appfwfield1
        url: http://url
        isregex: NOTREGEX
        comment: sample
