---
- name: Sample appfwgrpccontenttype playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwgrpccontenttype
      delegate_to: localhost
      netscaler.adc.appfwgrpccontenttype:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        grpccontenttypevalue: application/grpc-web+proto
