---
- name: Sample appfwhtmlerrorpage playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwhtmlerrorpage
      delegate_to: localhost
      netscaler.adc.appfwhtmlerrorpage:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        src: http://10.217.30.16/testsite/Signatures/44_38_1_36/credit_card.html
        name: Html_ Error_2
        nitro_operation: import
        '#nitro_operation': import
