---
- name: Sample appfwurlencodedformcontenttype playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwurlencodedformcontenttype
      delegate_to: localhost
      netscaler.adc.appfwurlencodedformcontenttype:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        urlencodedformcontenttypevalue: application/x-www-form-urlencoded.*
        isregex: REGEX
