---
- name: Sample appfwgrpcwebtextcontenttype playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwgrpcwebtextcontenttype
      delegate_to: localhost
      netscaler.adc.appfwgrpcwebtextcontenttype:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        grpcwebtextcontenttypevalue: application/grpc-web-text
