- name: Sample Playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Sample Task | appfwXMLContentType
      delegate_to: localhost
      netscaler.adc.appfwxmlcontenttype:
        state: present
        xmlcontenttypevalue: .*/xml
        isregex: REGEX
