---
- name: Sample appfwpolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure appfwpolicy
      delegate_to: localhost
      netscaler.adc.appfwpolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: pr_appfw_pol
        rule: HTTP.REQ.HEADER("Host").EXISTS
        profilename: pr_appfw
