---
- name: Sample arp playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure arp
      delegate_to: localhost
      netscaler.adc.arp:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        ipaddress: 177.0.0.31
        mac: 96:f1:a0:2b:98:1f
        ifnum: 1/2
