---
- name: Sample auditsyslogaction playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure auditsyslogaction
      delegate_to: localhost
      netscaler.adc.auditsyslogaction:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: act1121
        lbvservername: lb511
        loglevel:
          - ALL
        lsn: ENABLED
        transport: TCP
        maxlogdatasizetohold: '1000'
