---
- name: Sample auditmessageaction playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure auditmessageaction
      delegate_to: localhost
      netscaler.adc.auditmessageaction:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: sample
        loglevel: INFORMATIONAL
        stringbuilderexpr: client.ip.src
