---
- name: Sample auditsyslogglobal_auditsyslogpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure auditsyslogglobal_auditsyslogpolicy_binding
      delegate_to: localhost
      netscaler.adc.auditsyslogglobal_auditsyslogpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: sys_pol_name
        priority: '11'
