---
- name: Sample authenticationvserver playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationvserver
      delegate_to: localhost
      netscaler.adc.authenticationvserver:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: Citrix_AAA_vServer
        servicetype: SSL
        ipv46: 0.0.0.0
