---
- name: Sample authenticationvserver_auditnslogpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationvserver_auditnslogpolicy_binding
      delegate_to: localhost
      netscaler.adc.authenticationvserver_auditnslogpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_authnvs7
        policy: ia_nspol1
        priority: '111'
