---
- name: Sample authorizationpolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authorizationpolicy
      delegate_to: localhost
      netscaler.adc.authorizationpolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: EPAautho1
        rule: client.app.proc(notepad) exists
        action: ALLOW
