---
- name: Sample authenticationnegotiatepolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationnegotiatepolicy
      delegate_to: localhost
      netscaler.adc.authenticationnegotiatepolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: negpol
        rule: ns_true
        reqaction: neg1
