---
- name: Sample authenticationvserver_authenticationpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationvserver_authenticationpolicy_binding
      delegate_to: localhost
      netscaler.adc.authenticationvserver_authenticationpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: Citrix_AAA_vServer
        policy: OKta_SAML_External
        priority: '500'
        nextfactor: LDAP_Userextraction_External
        gotopriorityexpression: NEXT
