---
- name: Sample authenticationsamlpolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationsamlpolicy
      delegate_to: localhost
      netscaler.adc.authenticationsamlpolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: samlsecureauthidppol
        rule: ns_true
        reqaction: secureauth_idp
