---
- name: Sample authenticationoauthidpprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationoauthidpprofile
      delegate_to: localhost
      netscaler.adc.authenticationoauthidpprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: OAuthIDPProfileIDP
        relyingpartymetadataurl: https://10.221.136.42/oauth/idp/.well-known/openid-configuration
