---
- name: Sample authenticationpolicylabel_authenticationpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationpolicylabel_authenticationpolicy_binding
      delegate_to: localhost
      netscaler.adc.authenticationpolicylabel_authenticationpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        labelname: LDAP_Userextraction_External
        policyname: LDAP_userextraction_External_pol
        priority: '100'
        gotopriorityexpression: END
