---
- name: Sample authenticationtacacspolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationtacacspolicy
      delegate_to: localhost
      netscaler.adc.authenticationtacacspolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: primaryIPv4TACACSpolicy
        rule: ns_true
        reqaction: primaryIPv4TACACSaction
