---
- name: Sample authenticationvserver_authenticationloginschemapolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationvserver_authenticationloginschemapolicy_binding
      delegate_to: localhost
      netscaler.adc.authenticationvserver_authenticationloginschemapolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: auth
        policy: first_factor_schema
        priority: '1'
