---
- name: Sample authenticationcertaction playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationcertaction
      delegate_to: localhost
      netscaler.adc.authenticationcertaction:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ca5
        twofactor: 'ON'
        groupnamefield: Subject:OU
