---
- name: Sample authenticationloginschemapolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationloginschemapolicy
      delegate_to: localhost
      netscaler.adc.authenticationloginschemapolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: second_factor_schema
        rule: 'true'
        action: second_factor_schema_action
