---
- name: Sample authenticationradiuspolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationradiuspolicy
      delegate_to: localhost
      netscaler.adc.authenticationradiuspolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: test_radius
        rule: ns_true
        reqaction: test_radius_act
