---
- name: Sample authenticationvserver_authenticationwebauthpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationvserver_authenticationwebauthpolicy_binding
      delegate_to: localhost
      netscaler.adc.authenticationvserver_authenticationwebauthpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_authnvs71
        policy: webauthpol
