---
- name: Sample authenticationldappolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationldappolicy
      delegate_to: localhost
      netscaler.adc.authenticationldappolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: LDAP_Basic_Policy
        rule: ns_true
        reqaction: ldap_mgmt_act
