---
- name: Sample authenticationvserver_vpnportaltheme_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure authenticationvserver_vpnportaltheme_binding
      delegate_to: localhost
      netscaler.adc.authenticationvserver_vpnportaltheme_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: Citrix_AAA_vServer
        portaltheme: BX_Brand
