---
- name: Sample botsettings playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure botsettings
      delegate_to: localhost
      netscaler.adc.botsettings:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        proxyport: 0
