---
- name: Sample bridgegroup playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure bridgegroup
      delegate_to: localhost
      netscaler.adc.bridgegroup:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        id: '23'
        ipv6dynamicrouting: ENABLED
