---
- name: Sample cachecontentgroup playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure cachecontentgroup
      delegate_to: localhost
      netscaler.adc.cachecontentgroup:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: NSFEO
        maxressize: 1994752
