---
- name: Sample cachepolicylabel_cachepolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure cachepolicylabel_cachepolicy_binding
      delegate_to: localhost
      netscaler.adc.cachepolicylabel_cachepolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        labelname: _httpquicResBuiltinDefaults
        policyname: _personalizedRes
        priority: '800'
        gotopriorityexpression: END
