---
- name: Sample cacheselector playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure cacheselector
      delegate_to: localhost
      netscaler.adc.cacheselector:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        selectorname: n_XM_URL_10.100.39.132
        rule:
          - HTTP.REQ.URL.QUERY.VALUE("url")
