- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | callhome
      delegate_to: localhost
      netscaler.adc.callhome:
        state: present
        hbcustominterval: '30'
