---
- name: Sample channel playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure channel
      delegate_to: localhost
      netscaler.adc.channel:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        id: LA/4
        ifnum:
          - 1/3
        speed: AUTO
        flowctl: 'OFF'
        hamonitor: 'OFF'
        tagall: 'OFF'
        ifalias: alias1
        throughput: '23'
        bandwidthhigh: '23'
        bandwidthnormal: '23'
