---
- name: Sample cmpaction playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure cmpaction
      delegate_to: localhost
      netscaler.adc.cmpaction:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: Base_cmp_act1
        cmptype: compress
