---
- name: Sample cmppolicylabel playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure cmppolicylabel
      delegate_to: localhost
      netscaler.adc.cmppolicylabel:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        labelname: Base_cmp_pol_label
        type: RES
