---
- name: Sample crpolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure crpolicy
      delegate_to: localhost
      netscaler.adc.crpolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: crp1
        rule: 'true'
        action: origin
