---
- name: Sample crvserver playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure crvserver
      delegate_to: localhost
      netscaler.adc.crvserver:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: cr_fwd
        servicetype: HTTP
        ipv46: 1.1.1.2
        port: 80
        cachetype: FORWARD
