---
- name: Sample crvserver_crpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure crvserver_crpolicy_binding
      delegate_to: localhost
      netscaler.adc.crvserver_crpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: CR_v1
        policyname: CR_cspol1
        priority: '10'
