---
- name: Sample csparameter playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure csparameter
      delegate_to: localhost
      netscaler.adc.csparameter:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        stateupdate: ENABLED
