---
- name: Sample cspolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure cspolicy
      delegate_to: localhost
      netscaler.adc.cspolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: cs_pol
        rule: is_vpn_url
        action: cs_act
