---
- name: Sample csvserver playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure csvserver
      delegate_to: localhost
      netscaler.adc.csvserver:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ADNS_TCP_EXT
        servicetype: DNS_TCP
        ipv46: 10.189.1.7
        port: 53
        ipset: ipset_adns
        clttimeout: 180
        persistencetype: NONE
