---
- name: Sample csvserver_vpnvserver_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure csvserver_vpnvserver_binding
      delegate_to: localhost
      netscaler.adc.csvserver_vpnvserver_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: CS123
        vserver: vpn51
