---
- name: Sample csvserver_responderpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure csvserver_responderpolicy_binding
      delegate_to: localhost
      netscaler.adc.csvserver_responderpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: CSW_v1
        policyname: CSW_resppol1
        priority: '23'
        gotopriorityexpression: END
        bindpoint: REQUEST
        invoke: true
        labeltype: reqvserver
        labelname: CSW_invoke_labelname
