---
- name: Sample csvserver_rewritepolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure csvserver_rewritepolicy_binding
      delegate_to: localhost
      netscaler.adc.csvserver_rewritepolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: CSW_v1
        policyname: CSW_rwrtpol1
        priority: '23'
        gotopriorityexpression: END
        bindpoint: RESPONSE
        invoke: true
        labeltype: policylabel
        labelname: CSW_invoke_labelname
