---
- name: Sample csvserver_lbvserver_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure csvserver_lbvserver_binding
      delegate_to: localhost
      netscaler.adc.csvserver_lbvserver_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: vip_cs
        lbvserver: vip_lb
