---
- name: Sample dnsaddrec playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure dnsaddrec
      delegate_to: localhost
      netscaler.adc.dnsaddrec:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        hostname: e.root-servers.net
        ipaddress:
          - 192.203.230.10
        ttl: 3600000
