---
- name: Sample dnsnaptrrec playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure dnsnaptrrec
      delegate_to: localhost
      netscaler.adc.dnsnaptrrec:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        domain: citrix.com1
        order: '10'
        preference: '10'
        flags: U
        services: E2U+sip
        regexp: '!^.*$!sip:customer-service@example.com!'
        ttl: 3600
