---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | dnsnsRec
      delegate_to: localhost
      netscaler.adc.dnsnsrec:
        state: present
        domain: .
        nameserver: a.root-servers.net
        ttl: 3600000
