---
- name: Sample dnsnsrec playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure dnsnsrec
      delegate_to: localhost
      netscaler.adc.dnsnsrec:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        domain: .
        nameserver: m.root-servers.net
        ttl: 3600000
