---
- name: Sample Playbook for netscaler.adc.dnsproxyrecords
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Flush DNS Proxy records
      delegate_to: localhost
      netscaler.adc.dnsproxyrecords:
        state: flushed
