---
- name: Sample dnstxtrec playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure dnstxtrec
      delegate_to: localhost
      netscaler.adc.dnstxtrec:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        domain: sample2
        String:
          - sample
        ttl: 36000
