---
- name: Sample extendedmemoryparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure extendedmemoryparam
      delegate_to: localhost
      netscaler.adc.extendedmemoryparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        memlimit: 4380
