---
- name: Sample feoaction playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure feoaction
      delegate_to: localhost
      netscaler.adc.feoaction:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: allact_ns
        clientsidemeasurements: true
