---
- name: Sample feoglobal_feopolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure feoglobal_feopolicy_binding
      delegate_to: localhost
      netscaler.adc.feoglobal_feopolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: pol1_ns
        priority: '3'
        gotopriorityexpression: END
