---
- name: Sample feoparameter playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure feoparameter
      delegate_to: localhost
      netscaler.adc.feoparameter:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        jpegqualitypercent: '60'
        cssinlinethressize: '1024'
        jsinlinethressize: '1024'
        imginlinethressize: '1024'
