---
- name: Sample fis playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure fis
      delegate_to: localhost
      netscaler.adc.fis:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_fis11
