---
- name: Sample forwardingsession playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure forwardingsession
      delegate_to: localhost
      netscaler.adc.forwardingsession:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_forsess5
        nitro_operation: rm
        '#nitro_operation': rm
