---
- name: Sample gslbvserver_gslbservice_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure gslbvserver_gslbservice_binding
      delegate_to: localhost
      netscaler.adc.gslbvserver_gslbservice_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: backup_gslb_portal.bx.com
        servicename: GSLB_SVC_USE2_portal.bx.com
