---
- name: Sample gslbservice_dnsview_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure gslbservice_dnsview_binding
      delegate_to: localhost
      netscaler.adc.gslbservice_dnsview_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        servicename: gslbService1
        viewname: view1
        viewip: 2.2.2.1
