---
- name: Sample icaaccessprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure icaaccessprofile
      delegate_to: localhost
      netscaler.adc.icaaccessprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ipr
        clientclipboardredirection: DEFAULT
