---
- name: Sample icaglobal_icapolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure icaglobal_icapolicy_binding
      delegate_to: localhost
      netscaler.adc.icaglobal_icapolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: icapol2
        priority: '2'
        type: ICA_REQ_DEFAULT
