---
- name: Sample inatparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure inatparam
      delegate_to: localhost
      netscaler.adc.inatparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        nat46fragheader: DISABLED
