---
- name: Sample interface playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure interface
      delegate_to: localhost
      netscaler.adc.interface:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        hamonitor: 'OFF'
        haheartbeat: 'OFF'
        throughput: '0'
        bandwidthhigh: '0'
        bandwidthnormal: '0'
        intftype: Loopback
        ifnum:
          - LO/1
        interface_id: LO/1
