---
- name: Sample ipset_nsip_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure ipset_nsip_binding
      delegate_to: localhost
      netscaler.adc.ipset_nsip_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ipset_adns
        ipaddress:
          - 10.189.33.7
