---
- name: Sample ipsecprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure ipsecprofile
      delegate_to: localhost
      netscaler.adc.ipsecprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_ipsecpro10
        publickey: sample
        privatekey: sample
        peerpublickey: sample
        livenesscheckinterval: '23'
        replaywindowsize: '23'
        ikeretryinterval: '60'
        retransmissiontime: '23'
