---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: IPSET | ADD | --check
      delegate_to: localhost
      register: result
      check_mode: true
      tags: test
      netscaler.adc.ipset:
        state: present
        name: ipset-001
    - name: Assert | IPSET | ADD | --check
      tags: test
      ansible.builtin.assert:
        that:
          - "result.failed==false"
          - "result.changed==true"
    - name: IPSET | ADD
      delegate_to: localhost
      register: result
      check_mode: false
      tags: test
      netscaler.adc.ipset:
        state: present
        name: ipset-001
    - name: Assert | IPSET | ADD
      ansible.builtin.assert:
        that:
          - "result.failed==false"
          - "result.changed==true"
    - name: IPSET | ADD | idempotent
      delegate_to: localhost
      register: result
      check_mode: false
      tags: test
      netscaler.adc.ipset:
        state: present
        name: ipset-001
    - name: Assert | IPSET | ADD | idempotent
      tags: test
      ansible.builtin.assert:
        that:
          - "result.failed==false"
          - "result.changed==false"
    - name: IPSET | DELETE | --check
      delegate_to: localhost
      register: result
      check_mode: true
      tags: test
      netscaler.adc.ipset:
        state: absent
        name: ipset-001
    - name: Assert | IPSET | DELETE | --check
      tags: test
      ansible.builtin.assert:
        that:
          - "result.failed==false"
          - "result.changed==true"
    - name: IPSET | DELETE
      delegate_to: localhost
      register: result
      check_mode: false
      tags: test
      netscaler.adc.ipset:
        state: absent
        name: ipset-001
    - name: Assert | IPSET | DELETE
      ansible.builtin.assert:
        that:
          - "result.failed==false"
          - "result.changed==true"
    - name: IPSET | DELETE | idempotent
      delegate_to: localhost
      register: result
      check_mode: false
      tags: test
      netscaler.adc.ipset:
        state: absent
        name: ipset-001
    - name: Assert | IPSET | DELETE | idempotent
      tags: test
      ansible.builtin.assert:
        that:
          - "result.failed==false"
          - "result.changed==false"
