---
- name: Sample ipset playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure ipset
      delegate_to: localhost
      netscaler.adc.ipset:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ipset_adns
