---
- name: Sample iptunnel playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure iptunnel
      delegate_to: localhost
      netscaler.adc.iptunnel:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: t11
        remote: 1.1.1.14
        remotesubnetmask: 255.255.255.255
        local: 1.1.1.22
        protocol: VXLAN
