---
- name: Sample iptunnelparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure iptunnelparam
      delegate_to: localhost
      netscaler.adc.iptunnelparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        srciproundrobin: 'YES'
