---
- name: Sample l2param playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure l2param
      delegate_to: localhost
      netscaler.adc.l2param:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        returntoethernetsender: ENABLED
