---
- name: Sample l3param playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure l3param
      delegate_to: localhost
      netscaler.adc.l3param:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        icmperrgenerate: DISABLED
