---
- name: Sample Task
  hosts: localhost

  gather_facts: false

  tasks:
    - name: Sample playbook
      delegate_to: localhost
      netscaler.adc.l3param:
        state: present
        acllogtime: 3000
    - name: Sample playbook
      delegate_to: localhost
      netscaler.adc.l3param:
        state: absent # absent for l3param calls unset action
        acllogtime: "true"
