- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | lacp
      delegate_to: localhost
      netscaler.adc.lacp:
        state: present
        syspriority: '32768'
