---
- name: Sample lbmetrictable playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lbmetrictable
      delegate_to: localhost
      netscaler.adc.lbmetrictable:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        metrictable: LB_ia_metrictable3
