---
- name: Sample lbmetrictable_metric_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lbmetrictable_metric_binding
      delegate_to: localhost
      netscaler.adc.lbmetrictable_metric_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        metrictable: LB_ia_metrictable3
        metric: ia_metric
        snmpoid: 1.1.1.115.4.1.5951.4.1.1.46.3.9
