---
- name: Sample lbmonitor playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lbmonitor
      delegate_to: localhost
      netscaler.adc.lbmonitor:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        monitorname: Storefront
        type: STOREFRONT
        scriptname: nssf.pl
        dispatcherip: 127.0.0.1
        dispatcherport: 3013
        lrtm: DISABLED
        secure: 'YES'
        storename: Store
        storefrontcheckbackendservices: 'YES'
