---
- name: Sample lbmonitor_sslcertkey_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lbmonitor_sslcertkey_binding
      delegate_to: localhost
      netscaler.adc.lbmonitor_sslcertkey_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        monitorname: https
        certkeyname: myclient
