---
- name: Sample lbparameter playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lbparameter
      delegate_to: localhost
      netscaler.adc.lbparameter:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
