---
- name: Sample lbvserver_responderpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lbvserver_responderpolicy_binding
      delegate_to: localhost
      netscaler.adc.lbvserver_responderpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: v666
        policyname: P1
        priority: '5'
        bindpoint: REQUEST
