---
- name: Simple lbvserver_service_binding playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | lbvserver_service_binding
      delegate_to: localhost
      netscaler.adc.lbvserver_service_binding:
        # nsip: 10.0.0.1 # This can also be given via NETSCALER_NSIP environment variable
        # nitro_user: nitrouser # This can also be given via NETSCALER_NITRO_USER environment variable
        # nitro_pass: verysecretpassword # This can also be given via NETSCALER_NITRO_PASS environment variable
        # nitro_protocol: https # This can also be given via NETSCALER_NITRO_PROTOCOL environment variable
        # validate_certs: false # This can also be given via NETSCALER_VALIDATE_CERTS environment variable
        # save_config: false # This can also be given via NETSCALER_SAVE_CONFIG environment variable
        state: absent
        name: test_lbvser
        servicename: s1
        weight: 16
