---
- name: Sample locationparameter playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure locationparameter
      delegate_to: localhost
      netscaler.adc.locationparameter:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        q2label: Country_Code
        q3label: Subdivision_1_Name
        q4label: Subdivision_2_Name
        q5label: City
