---
- name: Sample lsnclient_network_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsnclient_network_binding
      delegate_to: localhost
      netscaler.adc.lsnclient_network_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        clientname: dsl_http
        network: 94.94.94.94
        netmask: 255.255.255.255
