---
- name: Sample lsnclient playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsnclient
      delegate_to: localhost
      netscaler.adc.lsnclient:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        clientname: dsl_http
