---
- name: Sample lsngroup playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsngroup
      delegate_to: localhost
      netscaler.adc.lsngroup:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        groupname: dsl_http
        clientname: dsl_http
