---
- name: Sample lsngroup_lsnsipalgprofile_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsngroup_lsnsipalgprofile_binding
      delegate_to: localhost
      netscaler.adc.lsngroup_lsnsipalgprofile_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        groupname: g15
        sipalgprofilename: sipalgprofile_udp
