---
- name: Sample lsngroup_lsnrtspalgprofile_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsngroup_lsnrtspalgprofile_binding
      delegate_to: localhost
      netscaler.adc.lsngroup_lsnrtspalgprofile_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        groupname: group12
        rtspalgprofilename: rtspprofile1
