---
- name: Sample lsngroup_lsnpool_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsngroup_lsnpool_binding
      delegate_to: localhost
      netscaler.adc.lsngroup_lsnpool_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        groupname: group4
        poolname: pool4
