---
- name: Sample lsnhttphdrlogprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsnhttphdrlogprofile
      delegate_to: localhost
      netscaler.adc.lsnhttphdrlogprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        httphdrlogprofilename: httplog
        logurl: ENABLED
        logmethod: ENABLED
        logversion: ENABLED
        loghost: ENABLED
