---
- name: Sample lsnip6profile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsnip6profile
      delegate_to: localhost
      netscaler.adc.lsnip6profile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ds1
        type: DS-Lite
        network6: 3ffe:100::1
