---
- name: Sample lsnlogprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsnlogprofile
      delegate_to: localhost
      netscaler.adc.lsnlogprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        logprofilename: msd
        logsubscrinfo: ENABLED
