---
- name: Sample lsnpool_lsnip_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsnpool_lsnip_binding
      delegate_to: localhost
      netscaler.adc.lsnpool_lsnip_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        poolname: pool4
        lsnip: 45.1.1.1-45.1.1.10
