---
- name: Sample lsnsipalgprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure lsnsipalgprofile
      delegate_to: localhost
      netscaler.adc.lsnsipalgprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        sipalgprofilename: sipalgprofile_udp
        registrationtimeout: '3600'
        sipdstportrange: '5060'
        siptransportprotocol: UDP
