---
- name: Sample mapbmr_bmrv4network_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure mapbmr_bmrv4network_binding
      delegate_to: localhost
      netscaler.adc.mapbmr_bmrv4network_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: bmr1
        network: 192.0.2.0
        netmask: 255.255.255.0
