---
- name: Sample mapdomain_mapbmr_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure mapdomain_mapbmr_binding
      delegate_to: localhost
      netscaler.adc.mapdomain_mapbmr_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: map1
        mapbmrname: bmr1
