---
- name: Sample mapdomain playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure mapdomain
      delegate_to: localhost
      netscaler.adc.mapdomain:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: map1
        mapdmrname: dmr1
