---
- name: Sample nat64 playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nat64
      delegate_to: localhost
      netscaler.adc.nat64:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_nat2
        acl6name: net_acl6
        netprofile: netpprof
