---
- name: Sample nd6ravariables playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nd6ravariables
      delegate_to: localhost
      netscaler.adc.nd6ravariables:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        vlan: '1'
