---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | netProfile
      delegate_to: localhost
      netscaler.adc.netprofile:
        state: present
        name: netprofile-001
        srcip: ipset-001
        mbf: DISABLED
