---
- name: Sample netprofile_srcportset_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure netprofile_srcportset_binding
      delegate_to: localhost
      netscaler.adc.netprofile_srcportset_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: np221
        srcportrange:
          - 1024-1026
