---
- name: Sample netprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure netprofile
      delegate_to: localhost
      netscaler.adc.netprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: tets_netprofile_dns
        srcip: 10.189.130.20
        mbf: ENABLED
