---
- name: Sample nsacl playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nsacl
      delegate_to: localhost
      netscaler.adc.nsacl:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        aclname: ACL_SF_Allow_USE1-B
        aclaction: ALLOW
        srcip: true
        srcipop: '='
        srcipval: 10.189.96.60
        destip: true
        destipop: '='
        destipdataset: SF_LBVIP
        priority: '15'
        kernelstate: SFAPPLIED61
