---
- name: Sample nsdhcpparams playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nsdhcpparams
      delegate_to: localhost
      netscaler.adc.nsdhcpparams:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        saveroute: 'ON'
