---
- name: Sample nsencryptionparams playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nsencryptionparams
      delegate_to: localhost
      netscaler.adc.nsencryptionparams:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        method: AES256
        keyvalue: REQ_PASSWORD
