---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | nshostName
      delegate_to: localhost
      netscaler.adc.nshostname:
        state: present
        hostname: ansible-test
