---
- name: Sample nshostname playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nshostname
      delegate_to: localhost
      netscaler.adc.nshostname:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        hostname: ns
