---
- name: Sample nshttpprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nshttpprofile
      delegate_to: localhost
      netscaler.adc.nshttpprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: nshttp_default_profile
        dropinvalreqs: ENABLED
