---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | nshttpProfile
      delegate_to: localhost
      netscaler.adc.nshttpprofile:
        state: present
        name: httpprofile-HTTP2-0
        http2: ENABLED
