---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | nsip
      delegate_to: localhost
      netscaler.adc.nsip:
        state: present
        ipaddress: 1.1.1.1
        netmask: 255.255.255.192
        type: VIP
    - name: Sample Task | nsip | 2
      delegate_to: localhost
      netscaler.adc.nsip:
        state: present
        ipaddress: 192.188.1.1
        netmask: 255.255.255.0
        vserver: DISABLED
        dynamicrouting: ENABLED
    - name: Sample Task | nsip | 3
      delegate_to: localhost
      netscaler.adc.nsip:
        state: present
        ipaddress: 192.179.1.1
        netmask: 255.255.255.255
        type: VIP
        arp: DISABLED
        snmp: DISABLED
        hostroute: ENABLED
        hostrtgw: 0.0.0.0
    - name: Sample Task | nsip | 4
      delegate_to: localhost
      netscaler.adc.nsip:
        state: present
        ipaddress: 192.188.1.2
        netmask: 255.255.0.0
        vserver: DISABLED
