---
- name: Sample nspartition_vlan_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nspartition_vlan_binding
      delegate_to: localhost
      netscaler.adc.nspartition_vlan_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        partitionname: p11
        vlan: '11'
