---
- name: Sample nspartition playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nspartition
      delegate_to: localhost
      netscaler.adc.nspartition:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        partitionname: p1
        vxlan: '1'
        nitro_operation: unbind
        '#nitro_operation': unbind
