---
- name: Sample nsparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nsparam
      delegate_to: localhost
      netscaler.adc.nsparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        cookieversion: '1'
