---
- name: Sample nspbrs playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nspbrs
      delegate_to: localhost
      netscaler.adc.nspbrs:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        action: apply
