---
- name: Sample nstcpparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure nstcpparam
      delegate_to: localhost
      netscaler.adc.nstcpparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        autosyncookietimeout: '100'
