---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | nsweblogparam
      delegate_to: localhost
      netscaler.adc.nsweblogparam:
        state: present
        buffersizemb: '3'
