---
- name: Sample onlinkipv6prefix playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure onlinkipv6prefix
      delegate_to: localhost
      netscaler.adc.onlinkipv6prefix:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        ipv6prefix: 2001::/64
        onlinkprefix: 'NO'
        autonomusprefix: 'NO'
        depricateprefix: 'YES'
        decrementprefixlifetimes: 'YES'
        prefixvalidelifetime: '30'
        prefixpreferredlifetime: '20'
