---
- name: Sample pcpprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure pcpprofile
      delegate_to: localhost
      netscaler.adc.pcpprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: pcp_profile_1
        mapping: ENABLED
