---
- name: Sample pcpserver playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure pcpserver
      delegate_to: localhost
      netscaler.adc.pcpserver:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: pcp_server_1
        port: 34
