---
- name: Sample policyparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure policyparam
      delegate_to: localhost
      netscaler.adc.policyparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        timeout: 5000
