---
- name: Sample policydataset playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure policydataset
      delegate_to: localhost
      netscaler.adc.policydataset:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: SF_LBVIP
        type: ipv4
