---
- name: Sample policystringmap playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure policystringmap
      delegate_to: localhost
      netscaler.adc.policystringmap:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_polstrmap1
