---
- name: Sample policyexpression playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure policyexpression
      delegate_to: localhost
      netscaler.adc.policyexpression:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: Sub_1471612160_23
        value: CLIENT.IP.SRC.IN_SUBNET(147.161.216.0/23)
