---
- name: Sample rdpclientprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure rdpclientprofile
      delegate_to: localhost
      netscaler.adc.rdpclientprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: rdpc2
        rdpurloverride: DISABLE
        audiocapturemode: ENABLE
        rdpfilename: mstsc.rdp
        rdpcustomparams: span monitors:i:1
        psk: test!@3
