---
- name: Sample rewritepolicylabel playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure rewritepolicylabel
      delegate_to: localhost
      netscaler.adc.rewritepolicylabel:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        labelname: ia_rwrtpolabl6
        transform: http_req
