---
- name: Sample rewriteparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure rewriteparam
      delegate_to: localhost
      netscaler.adc.rewriteparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        undefaction: RESET
        timeout: 5000
