---
- name: Sample rnatparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure rnatparam
      delegate_to: localhost
      netscaler.adc.rnatparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        tcpproxy: DISABLED
