---
- name: Sample rnat playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure rnat
      delegate_to: localhost
      netscaler.adc.rnat:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: RNAT_SF_Allow_USE1-A
        aclname: ACL_SF_Allow_USE1-A
