- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | rsskeytype
      delegate_to: localhost
      netscaler.adc.rsskeytype:
        state: present
        rsstype: ASYMMETRIC
