- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | service
      delegate_to: localhost
      netscaler.adc.service:
        state: present
        name: service-http
        servicetype: HTTP
        ipaddress: 172.18.0.4
        port: 5000
