- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | server
      delegate_to: localhost
      netscaler.adc.server:
        state: present
        name: 10.10.10.10
        ipaddress: 10.10.10.10
