---
- name: Sample servicegroup_servicegroupmember_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure servicegroup_servicegroupmember_binding
      delegate_to: localhost
      netscaler.adc.servicegroup_servicegroupmember_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        servicegroupname: CR_SVG
        ip: 172.168.1.20
        port: 80
