---
- name: Sample server playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure server
      delegate_to: localhost
      netscaler.adc.server:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: 10.79.42.253
        ipaddress: 10.79.42.253
