---
- name: Sample snmpview playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure snmpview
      delegate_to: localhost
      netscaler.adc.snmpview:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_snmpview1
        subtree: 1.3.6.1.4.1.5951.4.1.1.20
        type: included
