---
- name: Sample snmptrap playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure snmptrap
      delegate_to: localhost
      netscaler.adc.snmptrap:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        trapclass: specific
        trapdestination:
          - 10.189.64.10
        communityname: snmp
        allpartitions: ENABLED
