---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | snmpgroup
      delegate_to: localhost
      netscaler.adc.snmpgroup:
        state: present
        name: v3_grp
        securitylevel: noAuthNoPriv
        readviewname: v3_grp_view
