---
- name: Sample sslcertreq playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslcertreq
      delegate_to: localhost
      netscaler.adc.sslcertreq:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        reqfile: ssl_rsa_der_csr
        keyfile: ssl_rsa_der_key
        keyform: DER
        countryname: US
        statename: asda
        organizationname: asdad
        organizationunitname: adsada
        localityname: adsad
        commonname: asdsad
        emailaddress: adsad
        nitro_operation: create
        '#nitro_operation': create
