---
- name: Sample sslcertkey_sslocspresponder_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslcertkey_sslocspresponder_binding
      delegate_to: localhost
      netscaler.adc.sslcertkey_sslocspresponder_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        certkey: baluVpn2
