- name: Sample Playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Sample Task | sslcertKey
      delegate_to: localhost
      netscaler.adc.sslcertkey:
        state: present
        certkey: ns-server-certificate
        cert: ns-server.cert
        key: ns-server.key
        password: false
