---
- name: Sample sslcipher playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslcipher
      delegate_to: localhost
      netscaler.adc.sslcipher:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        ciphergroupname: ssllabs-blackstone
