---
- name: Sample sslcertkey playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslcertkey
      delegate_to: localhost
      netscaler.adc.sslcertkey:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        certkey: callback.blackstone.com
        linkcertkeyname: blackstone_sub
        nitro_operation: link
        '#nitro_operation': link
