---
- name: Sample ssldhparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure ssldhparam
      delegate_to: localhost
      netscaler.adc.ssldhparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        dhfile: dfile
        bits: '512'
        gen: '2'
        nitro_operation: create
        '#nitro_operation': create
