---
- name: Sample sslprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslprofile
      delegate_to: localhost
      netscaler.adc.sslprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ns_default_ssl_profile_internal_frontend_service
