---
- name: Sample sslprofile_ecccurve_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslprofile_ecccurve_binding
      delegate_to: localhost
      netscaler.adc.sslprofile_ecccurve_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: blackstone_ssl_profile
        ecccurvename: P_521
