---
- name: Sample sslpolicylabel playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslpolicylabel
      delegate_to: localhost
      netscaler.adc.sslpolicylabel:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        labelname: invoke_labelname
        type: CONTROL
