---
- name: Sample sslpolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslpolicy
      delegate_to: localhost
      netscaler.adc.sslpolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: new_XM_MDM_titan.dnpg-blr.com_POLICY1
        rule: CLIENT.SSL.CLIENT_CERT.EXISTS
        action: _XM_MDM_titan.dnpg-blr.com_ACTION
