---
- name: Sample sslparameter playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslparameter
      delegate_to: localhost
      netscaler.adc.sslparameter:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        defaultprofile: ENABLED
