---
- name: Sample sslrsakey playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslrsakey
      delegate_to: localhost
      netscaler.adc.sslrsakey:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        keyfile: ssl_rsa_der_key
        bits: '2048'
        exponent: '3'
        keyform: DER
        nitro_operation: create
        '#nitro_operation': create
