---
- name: Sample sslservice_sslcertkey_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslservice_sslcertkey_binding
      delegate_to: localhost
      netscaler.adc.sslservice_sslcertkey_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        servicename: nsrpcs-127.0.0.1-3008
        certkeyname: ns-server-certificate
