---
- name: Sample sslservice_sslcipher_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslservice_sslcipher_binding
      delegate_to: localhost
      netscaler.adc.sslservice_sslcipher_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        servicename: ssl
        ciphername: AES-GCM
