---
- name: Sample sslservicegroup_sslcertkey_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure sslservicegroup_sslcertkey_binding
      delegate_to: localhost
      netscaler.adc.sslservicegroup_sslcertkey_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        servicegroupname: ssl_sg4
        certkeyname: ssl_cert_ca20
