---
- name: Sample streamselector playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure streamselector
      delegate_to: localhost
      netscaler.adc.streamselector:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: insight_sel
        rule:
          - http.req.url
