---
- name: Sample streamidentifier playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure streamidentifier
      delegate_to: localhost
      netscaler.adc.streamidentifier:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: xyz
        selectorname: insight_sel
        appflowlog: ENABLED
        tracktransactions: RESPTIME
        maxtransactionthreshold: '2'
        mintransactionthreshold: '1'
        acceptancethreshold: '100.000000'
