---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | subscribergxInterface
      delegate_to: localhost
      netscaler.adc.subscribergxinterface:
        state: present
        pcrfrealm: pcrf.com
        servicepathavp:
          - 262099
        servicepathvendorid: 3845
