- name: Sample Playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Sample Task | systemparameter
      delegate_to: localhost
      netscaler.adc.systemparameter:
        state: present
        promptstring: '%u@%s'
