---
- name: Sample systemextramgmtcpu playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure systemextramgmtcpu
      delegate_to: localhost
      netscaler.adc.systemextramgmtcpu:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
