---
- name: Sample systemglobal_authenticationtacacspolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure systemglobal_authenticationtacacspolicy_binding
      delegate_to: localhost
      netscaler.adc.systemglobal_authenticationtacacspolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: acsPolicy1
        priority: '1'
