---
- name: Sample systemuser playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure systemuser
      delegate_to: localhost
      netscaler.adc.systemuser:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        username: GD-CTRLUPADC-P-APP
        password: REQ_PASSWORD
        externalauth: DISABLED
        timeout: 900
