---
- name: Sample systemglobal_authenticationpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure systemglobal_authenticationpolicy_binding
      delegate_to: localhost
      netscaler.adc.systemglobal_authenticationpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: ldap_mgmt_pol
        priority: '100'
        gotopriorityexpression: NEXT
