- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | systemuser
      delegate_to: localhost
      netscaler.adc.systemuser:
        state: present
        username: nsroot
        timeout: 900
    - name: Sample Task | systemuser | 2
      delegate_to: localhost
      netscaler.adc.systemuser:
        state: present
        username: user_adm1
        password: pwd_adm1
