- name: Sample Playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Sample Task | systemgroup
      delegate_to: localhost
      netscaler.adc.systemgroup:
        state: present
        groupname: sys-group1
        promptstring: '[%T] %u@%h/%s'
