---
- name: Sample tmglobal_tmtrafficpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure tmglobal_tmtrafficpolicy_binding
      delegate_to: localhost
      netscaler.adc.tmglobal_tmtrafficpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: ia_tmtrafpol1
        priority: '1'
