---
- name: Sample tunnelglobal_tunneltrafficpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure tunnelglobal_tunneltrafficpolicy_binding
      delegate_to: localhost
      netscaler.adc.tunnelglobal_tunneltrafficpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        policyname: ns_tunnel_nocmp
