---
- name: Sample tunneltrafficpolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure tunneltrafficpolicy
      delegate_to: localhost
      netscaler.adc.tunneltrafficpolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: compress
        rule: url == /*.asp
