- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | videooptimizationparameter
      delegate_to: localhost
      netscaler.adc.videooptimizationparameter:
        state: present
        randomsamplingpercentage: 0.0
