---
- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | vlan
      delegate_to: localhost
      netscaler.adc.vlan:
        state: present
        id: '301'
        aliasname: client_side_network
