---
- name: Sample vlan playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vlan
      delegate_to: localhost
      netscaler.adc.vlan:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        vlanid: '10'
