---
- name: Sample vpnalwaysonprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnalwaysonprofile
      delegate_to: localhost
      netscaler.adc.vpnalwaysonprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: aop1
        networkaccessonvpnfailure: fullAccess
        clientcontrol: DENY
        locationbasedvpn: Remote
