---
- name: Sample vpnclientlessaccessprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnclientlessaccessprofile
      delegate_to: localhost
      netscaler.adc.vpnclientlessaccessprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        profilename: ia_cltlsacsprof1
