---
- name: Sample vpneula playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpneula
      delegate_to: localhost
      netscaler.adc.vpneula:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: e2
