---
- name: Sample vpnformssoaction playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnformssoaction
      delegate_to: localhost
      netscaler.adc.vpnformssoaction:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_ssoact1
        actionurl: /owa/auth/owaauth.dll
        userfield: user
        passwdfield: freebsd
        ssosuccessrule: HTTP.RES.IS_VALID
