---
- name: Sample vpnglobal_vpneula_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnglobal_vpneula_binding
      delegate_to: localhost
      netscaler.adc.vpnglobal_vpneula_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        eula: e1
