---
- name: Sample vpnglobal_staserver_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnglobal_staserver_binding
      delegate_to: localhost
      netscaler.adc.vpnglobal_staserver_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        staserver: https://use1bxctxcca03.blackstone.com
