---
- name: Sample vpnglobal_vpnportaltheme_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnglobal_vpnportaltheme_binding
      delegate_to: localhost
      netscaler.adc.vpnglobal_vpnportaltheme_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        portaltheme: p2
