---
- name: Sample vpnintranetapplication playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnintranetapplication
      delegate_to: localhost
      netscaler.adc.vpnintranetapplication:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        intranetapplication: intra_app21
        protocol: TCP
        destip: 10.100.0.57
        interception: PROXY
