---
- name: Sample vpnportaltheme playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnportaltheme
      delegate_to: localhost
      netscaler.adc.vpnportaltheme:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: BX_Brand
        basetheme: RfWebUI
