---
- name: Sample vpnparameter playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnparameter
      delegate_to: localhost
      netscaler.adc.vpnparameter:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        forcecleanup:
          - none
        clientconfiguration:
          - all
