---
- name: Sample vpnpcoipprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnpcoipprofile
      delegate_to: localhost
      netscaler.adc.vpnpcoipprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
