- name: Sample Playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sample Task | vpnparameter
      delegate_to: localhost
      netscaler.adc.vpnparameter:
        state: present
        forcecleanup:
          - none
        clientconfiguration:
          - trace
