---
- name: Sample vpnsamlssoprofile playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnsamlssoprofile
      delegate_to: localhost
      netscaler.adc.vpnsamlssoprofile:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: new
        assertionconsumerserviceurl: http://a.com
        relaystaterule: http.req.url
