---
- name: Sample vpntrafficpolicy playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpntrafficpolicy
      delegate_to: localhost
      netscaler.adc.vpntrafficpolicy:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ia_trafpol1
        rule: ns_true
        action: ia_trafact1
