---
- name: Sample vpnurl playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnurl
      delegate_to: localhost
      netscaler.adc.vpnurl:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        urlname: url3
        linkname: url3
        actualurl: https://a.c.com/
        ssotype: samlauth
        samlssoprofile: new
