---
- name: Sample vpnvserver_vpnnexthopserver_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnvserver_vpnnexthopserver_binding
      delegate_to: localhost
      netscaler.adc.vpnvserver_vpnnexthopserver_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: dh
        nexthopserver: fqdn
