---
- name: Sample vpnvserver_staserver_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnvserver_staserver_binding
      delegate_to: localhost
      netscaler.adc.vpnvserver_staserver_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: portal.bx.com
        staserver: https://use1bxctxccp01.blackstone.com
