---
- name: Sample vpnvserver_authenticationlocalpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnvserver_authenticationlocalpolicy_binding
      delegate_to: localhost
      netscaler.adc.vpnvserver_authenticationlocalpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: callbackvs
        policy: NS_GATEWAY_DEFAULT_LOCAL_POL1
        priority: '64000'
