---
- name: Sample vpnvserver playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnvserver
      delegate_to: localhost
      netscaler.adc.vpnvserver:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: CitrixAccessCallback
        servicetype: SSL
        ipv46: 10.189.130.19
        port: 443
        downstateflush: DISABLED
        listenpolicy: NONE
