---
- name: Sample vpnvserver_authenticationldappolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnvserver_authenticationldappolicy_binding
      delegate_to: localhost
      netscaler.adc.vpnvserver_authenticationldappolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: ns.pcoip.net
        policy: ldap24
        priority: '100'
