---
- name: Sample vpnvserver_cachepolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnvserver_cachepolicy_binding
      delegate_to: localhost
      netscaler.adc.vpnvserver_cachepolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: CitrixAccessCallback
        policy: _noCacheRest
        priority: '20'
        gotopriorityexpression: END
        bindpoint: RESPONSE
