---
- name: Sample vpnvserver_vpnsessionpolicy_binding playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vpnvserver_vpnsessionpolicy_binding
      delegate_to: localhost
      netscaler.adc.vpnvserver_vpnsessionpolicy_binding:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: portal.bx.com
        policy: External_receiver_session_pol
        priority: '130'
        gotopriorityexpression: NEXT
        bindpoint: REQUEST
