---
- name: Sample vrid playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vrid
      delegate_to: localhost
      netscaler.adc.vrid:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        id: '100'
        preemptiondelaytimer: 100
