---
- name: Sample vridparam playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vridparam
      delegate_to: localhost
      netscaler.adc.vridparam:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        sendtomaster: ENABLED
