---
- name: Sample vxlanvlanmap playbook
  hosts: demo_netscalers
  gather_facts: false
  tasks:
    - name: Configure vxlanvlanmap
      delegate_to: localhost
      netscaler.adc.vxlanvlanmap:
        nsip: '{{ nsip }}'
        nitro_user: '{{ nitro_user }}'
        nitro_pass: '{{ nitro_pass }}'
        validate_certs: '{{ validate_certs }}'
        state: present
        name: v2
