---
name: ansible-lint
on:
  workflow_dispatch:
  pull_request:
    paths-ignore: 
      - .github/**
      - assets/**
      - docs/**
      - .whitesource
      - .yamlfmt
      - .yamllint
  push:
    paths-ignore:
      - .github/**
      - assets/**
      - docs/**
      - .whitesource
      - .yamlfmt
      - .yamllint
jobs:
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ansible_lint_result.sarif
